project_id = "nqebjeyyslscxnjvsysb"

[functions.send-confirmation-email]
verify_jwt = false

[functions.confirm-email]
verify_jwt = false

[functions.send-recovery-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.resend-welcome-email]
verify_jwt = false

[functions.hotmart-webhook]
verify_jwt = false

[functions.runninghub-flyer-maker]
verify_jwt = false

[functions.runninghub-queue-manager]
verify_jwt = false

[functions.runninghub-webhook]
verify_jwt = false
